package response

import (
	"strings"

	"github.com/gin-gonic/gin"
)

const (
	errorLocaleChinese = "zh"
	errorLocaleEnglish = "en"
)

var localizedErrorMessages = map[string]map[string]string{
	errorLocaleChinese: {
		"AUTH_REQUIRED":                                "请先登录后再操作",
		"UNAUTHORIZED":                                 "请先登录后再操作",
		"INVALID_USER":                                 "用户不存在或登录状态无效",
		"BACKEND_MODE_ADMIN_ONLY":                      "后端模式已启用，仅允许管理员登录",
		"SERVICE_UNAVAILABLE":                          "服务暂时不可用，请稍后重试",
		"CONFIG_NOT_READY":                             "系统配置尚未就绪",
		"VALIDATION_ERROR":                             "请求参数校验失败",
		"INVALID_REQUEST":                              "请求参数无效",
		"OAUTH_DISABLED":                               "第三方登录未启用",
		"PENDING_AUTH_NOT_READY":                       "授权服务暂时不可用，请稍后重试",
		"PENDING_AUTH_SESSION_INVALID":                 "授权会话无效或已过期，请重新发起授权",
		"PENDING_AUTH_TARGET_USER_MISMATCH":            "授权会话必须由指定用户完成",
		"USER_EMAIL_CONFLICT":                          "该邮箱匹配到多个用户，请联系管理员处理",
		"AUTH_IDENTITY_OWNERSHIP_CONFLICT":             "该第三方身份已绑定到其他用户",
		"AUTH_IDENTITY_CHANNEL_OWNERSHIP_CONFLICT":     "该第三方身份通道已绑定到其他用户",
		"SUBSCRIPTION_NOT_FOUND":                       "订阅不存在",
		"SUBSCRIPTION_EXPIRED":                         "订阅已过期",
		"SUBSCRIPTION_SUSPENDED":                       "订阅已暂停",
		"SUBSCRIPTION_ALREADY_EXISTS":                  "该用户已拥有此套餐订阅",
		"SUBSCRIPTION_ASSIGN_CONFLICT":                 "该用户已有订阅，且本次分配内容与现有订阅不一致",
		"SUBSCRIPTION_DUPLICATE_CONFIRMATION_REQUIRED": "该用户已拥有此套餐订阅，确认后将覆盖旧订阅",
		"SUBSCRIPTION_NOT_REVOKED":                     "订阅未撤销，无法恢复",
		"SUBSCRIPTION_RESTORE_CONFLICT":                "该用户已存在同套餐订阅，无法恢复",
		"GROUP_NOT_SUBSCRIPTION_TYPE":                  "目标分组不是订阅套餐类型",
		"DAILY_LIMIT_EXCEEDED":                         "今日用量已达到上限",
		"WEEKLY_LIMIT_EXCEEDED":                        "本周用量已达到上限",
		"MONTHLY_LIMIT_EXCEEDED":                       "本月用量已达到上限",
		"TOTAL_LIMIT_EXCEEDED":                         "总用量已达到上限",
		"SUBSCRIPTION_NIL_INPUT":                       "订阅参数不能为空",
		"ADJUST_WOULD_EXPIRE":                          "调整后订阅会立即过期，请输入更大的天数",
		"CANNOT_SHORTEN_EXPIRED":                       "已过期订阅不能缩短有效期",
		"OPS_REPO_UNAVAILABLE":                         "运维日志服务暂时不可用",
		"OPS_FILTER_REQUIRED":                          "缺少查询条件",
		"OPS_TIME_RANGE_REQUIRED":                      "必须提供开始时间和结束时间",
		"OPS_TIME_RANGE_INVALID":                       "开始时间不能晚于结束时间",
		"OPS_ERROR_NOT_FOUND":                          "未找到对应错误日志",
		"OPS_ERROR_INVALID_ID":                         "错误日志 ID 无效",
		"OPS_ERROR_LOAD_FAILED":                        "读取错误日志失败",
		"TURNSTILE_VERIFICATION_FAILED":                "人机验证失败，请重试",
		"TURNSTILE_NOT_CONFIGURED":                     "人机验证尚未配置",
		"TURNSTILE_INVALID_SECRET_KEY":                 "人机验证密钥无效",
		"TOTP_NOT_ENABLED":                             "两步验证功能未启用",
		"TOTP_ALREADY_ENABLED":                         "该账号已启用两步验证",
		"TOTP_NOT_SETUP":                               "该账号尚未设置两步验证",
		"TOTP_INVALID_CODE":                            "两步验证码无效",
		"TOTP_SETUP_EXPIRED":                           "两步验证设置会话已过期",
		"TOTP_TOO_MANY_ATTEMPTS":                       "验证尝试次数过多，请稍后再试",
		"TOTP_VERIFY_ERROR":                            "两步验证失败，请重试",
		"VERIFY_CODE_REQUIRED":                         "请输入邮箱验证码",
		"PASSWORD_REQUIRED":                            "请输入密码",
		"EMAIL_VERIFY_NOT_ENABLED":                     "邮箱验证功能未启用",
		"REDEEM_CODE_EXPIRY_CONFLICT":                  "不能同时设置固定过期时间和有效天数",
		"REDEEM_CODE_EXPIRES_IN_DAYS_INVALID":          "有效天数必须大于 0",
		"REDEEM_CODE_EXPIRES_AT_INVALID":               "过期时间必须晚于当前时间",
		"REDEEM_CODE_CONFLICT":                         "兑换码冲突或已被其他用户使用",
		"ACCOUNT_NIL_INPUT":                            "账号参数不能为空",
		"ACCOUNT_NOT_FOUND":                            "账号不存在",
		"ACCOUNT_NOT_IN_FALLBACK":                      "账号未处于回退状态",
		"API_KEY_EXISTS":                               "API Key 已存在",
		"API_KEY_EXPIRED":                              "API Key 已过期",
		"API_KEY_INACTIVE":                             "API Key 已停用",
		"API_KEY_INVALID_CHARS":                        "API Key 包含无效字符",
		"API_KEY_NOT_FOUND":                            "API Key 不存在",
		"API_KEY_QUOTA_EXHAUSTED":                      "API Key 额度已用完",
		"API_KEY_RATE_1D_EXCEEDED":                     "API Key 今日用量已达到上限",
		"API_KEY_RATE_5H_EXCEEDED":                     "API Key 5 小时用量已达到上限",
		"API_KEY_RATE_7D_EXCEEDED":                     "API Key 7 天用量已达到上限",
		"API_KEY_RATE_LIMITED":                         "API Key 请求过于频繁，请稍后重试",
		"API_KEY_TOO_SHORT":                            "API Key 长度过短",
		"BALANCE_NOT_ENOUGH":                           "余额不足",
		"INSUFFICIENT_BALANCE":                         "余额不足",
		"BALANCE_PAYMENT_DISABLED":                     "余额支付未启用",
		"BILLING_SERVICE_ERROR":                        "计费服务暂时不可用",
		"CANCEL_RATE_LIMITED":                          "取消操作过于频繁，请稍后重试",
		"CHANNEL_EXISTS":                               "渠道已存在",
		"CHANNEL_NOT_FOUND":                            "渠道不存在",
		"EMAIL_EXISTS":                                 "邮箱已被使用",
		"EMAIL_NOT_CONFIGURED":                         "邮箱服务未配置",
		"EMAIL_NOT_FOUND":                              "邮箱不存在",
		"EMAIL_RESERVED":                               "该邮箱不可使用",
		"EMAIL_SUFFIX_NOT_ALLOWED":                     "该邮箱后缀不允许注册",
		"EMAIL_VERIFY_REQUIRED":                        "请先完成邮箱验证",
		"FORBIDDEN":                                    "无权执行此操作",
		"GROUP_EXISTS":                                 "分组已存在",
		"GROUP_IS_SUBSCRIPTION":                        "该分组是订阅套餐分组",
		"GROUP_NOT_ACTIVE":                             "分组未启用",
		"GROUP_NOT_ALLOWED":                            "当前用户不能使用该分组",
		"GROUP_NOT_EXCLUSIVE":                          "该分组不是独占分组",
		"GROUP_NOT_FOUND":                              "分组不存在",
		"GROUP_RPM_EXCEEDED":                           "分组请求频率已达到上限",
		"GROUP_TYPE_MISMATCH":                          "分组类型不匹配",
		"INSUFFICIENT_PERMISSIONS":                     "权限不足",
		"INVALID_AMOUNT":                               "金额无效",
		"INVALID_CHANNEL_ID":                           "渠道 ID 无效",
		"INVALID_CREDENTIALS":                          "账号或密码错误",
		"INVALID_EMAIL":                                "邮箱格式无效",
		"INVALID_GROUP_ID":                             "分组 ID 无效",
		"INVALID_GROUP_FILTER":                         "分组筛选条件无效",
		"INVALID_INPUT":                                "输入参数无效",
		"INVALID_MODE":                                 "模式无效",
		"INVALID_MODERATION_TEST_IMAGE":                "内容审计测试图片无效",
		"INVALID_OUT_TRADE_NO":                         "商户订单号无效",
		"INVALID_PLATFORM":                             "平台无效",
		"INVALID_STATUS":                               "状态无效",
		"NOT_FOUND":                                    "记录不存在",
		"ORDER_EXPIRED":                                "订单已过期",
		"ORDER_NOT_FOUND":                              "订单不存在",
		"PAYMENT_DISABLED":                             "支付功能未启用",
		"PAYMENT_GATEWAY_ERROR":                        "支付网关异常，请稍后重试",
		"PLAN_GROUP_REQUIRED":                          "请选择套餐分组",
		"PLAN_NAME_REQUIRED":                           "请输入套餐名称",
		"PLAN_NOT_FOUND":                               "套餐不存在",
		"PLAN_NOT_AVAILABLE":                           "套餐不可用",
		"PLAN_ORIGINAL_PRICE_INVALID":                  "套餐原价无效",
		"PLAN_PRICE_INVALID":                           "套餐价格无效",
		"PLAN_VALIDITY_REQUIRED":                       "套餐有效期不能为空",
		"PLAN_VALIDITY_UNIT_REQUIRED":                  "请选择套餐有效期单位",
		"PENDING_ORDERS":                               "存在待处理订单，暂时不能执行该操作",
		"PAYMENT_PROVIDER_MISCONFIGURED":               "支付渠道配置不完整，请联系管理员",
		"REDEEM_CODE_BATCH_UPDATE_EMPTY":               "没有可更新的兑换码",
		"REDEEM_CODE_BATCH_UPDATE_IDS_REQUIRED":        "请选择要更新的兑换码",
		"REDEEM_CODE_BATCH_UPDATE_INVALID":             "批量更新兑换码参数无效",
		"REDEEM_CODE_BATCH_UPDATE_INVALID_ID":          "兑换码 ID 无效",
		"REDEEM_CODE_CORE_FIELDS_IMMUTABLE":            "已使用的兑换码不能修改核心字段",
		"REDEEM_CODE_DELETE_USED":                      "已使用的兑换码不能删除",
		"REDEEM_CODE_EXPIRED":                          "兑换码已过期",
		"REDEEM_CODE_GROUP_ID_INVALID":                 "兑换码分组无效",
		"REDEEM_CODE_INVALID":                          "兑换码无效",
		"REDEEM_CODE_LOCKED":                           "兑换码正在处理中，请稍后重试",
		"REDEEM_CODE_NOT_FOUND":                        "兑换码不存在",
		"REDEEM_CODE_STATUS_INVALID":                   "兑换码状态无效",
		"REDEEM_CODE_UNSUPPORTED_TYPE":                 "兑换码类型不支持",
		"REDEEM_CODE_USED":                             "兑换码已被使用",
		"REDEEM_RATE_LIMITED":                          "兑换过于频繁，请稍后重试",
		"SUBSCRIPTION_INVALID":                         "订阅无效或已过期",
		"SUBSCRIPTION_REQUIRED":                        "当前分组需要有效订阅",
		"USER_NOT_FOUND":                               "用户不存在",
		"USER_DISABLED":                                "用户已被禁用",
		"USER_INACTIVE":                                "用户未启用",
		"USER_NOT_ACTIVE":                              "用户未启用",
		"USER_PLATFORM_DAILY_QUOTA_EXHAUSTED":          "该平台今日额度已用完",
		"USER_PLATFORM_WEEKLY_QUOTA_EXHAUSTED":         "该平台本周额度已用完",
		"USER_PLATFORM_MONTHLY_QUOTA_EXHAUSTED":        "该平台本月额度已用完",
		"USER_REFUND_DISABLED":                         "该用户不允许退款",
		"USER_RPM_EXCEEDED":                            "用户请求频率已达到上限",
		"AVATAR_INVALID":                               "头像无效",
		"AVATAR_NOT_IMAGE":                             "头像文件不是图片",
		"AVATAR_TOO_LARGE":                             "头像文件过大",
		"AFFILIATE_ALREADY_BOUND":                      "该用户已绑定推广关系",
		"AFFILIATE_CODE_INVALID":                       "推广码无效",
		"AFFILIATE_CODE_TAKEN":                         "推广码已被使用",
		"AFFILIATE_PROFILE_NOT_FOUND":                  "推广配置不存在",
		"AFFILIATE_QUOTA_EMPTY":                        "推广额度不能为空",
		"ANNOUNCEMENT_INPUT_REQUIRED":                  "公告参数不能为空",
		"ANNOUNCEMENT_INVALID_TARGET":                  "公告定向规则无效",
		"ANNOUNCEMENT_NOT_FOUND":                       "公告不存在",
		"ANNOUNCEMENT_STATUS_INVALID":                  "公告状态无效",
		"ANNOUNCEMENT_TITLE_INVALID":                   "公告标题无效",
		"ATTRIBUTE_DEFINITION_NOT_FOUND":               "属性定义不存在",
		"ATTRIBUTE_KEY_EXISTS":                         "属性键已存在",
		"ATTRIBUTE_VALIDATION_FAILED":                  "属性校验失败",
		"AUTH_IDENTITY_BIND_FAILED":                    "绑定第三方身份失败",
		"AUTH_IDENTITY_CHANNEL_LOOKUP_FAILED":          "检查第三方身份通道失败",
		"AUTH_IDENTITY_EMAIL_MISMATCH":                 "第三方身份邮箱与当前邮箱不一致",
		"AUTH_IDENTITY_LOOKUP_FAILED":                  "检查第三方身份失败",
		"AUTH_IDENTITY_USER_LOOKUP_FAILED":             "读取第三方身份用户失败",
		"BACKUP_IN_PROGRESS":                           "备份任务正在执行中",
		"BACKUP_NOT_COMPLETED":                         "备份任务尚未完成",
		"BACKUP_NOT_FOUND":                             "备份不存在",
		"BACKUP_RECORDS_CORRUPT":                       "备份记录损坏",
		"BACKUP_S3_CONFIG_CORRUPT":                     "S3 备份配置损坏",
		"BACKUP_S3_NOT_CONFIGURED":                     "S3 备份尚未配置",
		"CONTENT_MODERATION_HASH_CACHE_UNAVAILABLE":    "内容审计哈希缓存暂时不可用",
		"IDENTITY_PROVIDER_INVALID":                    "第三方身份提供方无效",
		"IDENTITY_REDIRECT_INVALID":                    "第三方登录跳转地址无效",
		"OAUTH_BROWSER_SESSION_GEN_FAILED":             "生成授权浏览器会话失败",
		"OAUTH_BUILD_URL_FAILED":                       "生成授权链接失败",
		"OAUTH_CONFIG_INVALID":                         "第三方登录配置无效",
		"OAUTH_CONTEXT_ENCODE_FAILED":                  "编码授权上下文失败",
		"OAUTH_EMAIL_NOT_VERIFIED":                     "第三方账号邮箱尚未验证",
		"OAUTH_INVITATION_REQUIRED":                    "该第三方账号需要邀请码才能注册",
		"OAUTH_NONCE_GEN_FAILED":                       "生成授权 nonce 失败",
		"OAUTH_PKCE_GEN_FAILED":                        "生成授权 PKCE 校验失败",
		"OAUTH_PROVIDER_INVALID":                       "第三方登录提供方无效",
		"OAUTH_PROVIDER_NOT_FOUND":                     "第三方登录提供方不存在",
		"OAUTH_STATE_GEN_FAILED":                       "生成授权 state 失败",
		"OAUTH_SUBJECT_MISSING":                        "第三方账号缺少用户标识",
		"OPS_ALERT_EVENT_NOT_FOUND":                    "告警事件不存在",
		"OPS_ALERT_RULE_NOT_FOUND":                     "告警规则不存在",
		"OPS_DISABLED":                                 "运维监控未启用",
		"OPS_GROUP_ID_INVALID":                         "运维分组 ID 无效",
		"OPS_PAGE_INVALID":                             "页码无效",
		"OPS_PAGE_SIZE_INVALID":                        "分页大小无效",
		"OPS_PAGINATION_CONFLICT":                      "分页参数冲突",
		"OPS_PREAGG_NOT_READY":                         "预聚合数据尚未就绪",
		"OPS_SYSTEM_LOG_CLEANUP_FAILED":                "清理系统日志失败",
		"OPS_SYSTEM_LOG_CLEANUP_FILTER_REQUIRED":       "清理系统日志需要筛选条件",
		"OPS_SYSTEM_LOG_CLEANUP_INVALID_OPERATOR":      "系统日志清理操作人无效",
		"OPS_SYSTEM_LOG_CLEANUP_INVALID_RANGE":         "系统日志清理时间范围无效",
		"OPS_SYSTEM_LOG_LIST_FAILED":                   "读取系统日志失败",
		"OPS_TIME_RANGE_TOO_LARGE":                     "查询时间范围过大",
		"OPS_TOPN_INVALID":                             "TopN 参数无效",
		"PASSWORD_INCORRECT":                           "密码错误",
		"PASSWORD_RESET_DISABLED":                      "密码重置功能未启用",
		"PASSWORD_TOO_SHORT":                           "密码长度过短",
		"PENDING_AUTH_ADOPTION_APPLY_FAILED":           "应用待处理授权资料失败",
		"PENDING_AUTH_ADOPTION_LOAD_FAILED":            "读取待处理授权资料失败",
		"PENDING_AUTH_ADOPTION_SAVE_FAILED":            "保存待处理授权资料失败",
		"PENDING_AUTH_BIND_APPLY_FAILED":               "绑定待处理授权身份失败",
		"PENDING_AUTH_BROWSER_MISMATCH":                "授权浏览器会话不匹配",
		"PENDING_AUTH_CODE_CONSUMED":                   "授权码已使用",
		"PENDING_AUTH_CODE_EXPIRED":                    "授权码已过期",
		"PENDING_AUTH_CODE_INVALID":                    "授权码无效",
		"PENDING_AUTH_COMPLETION_INVALID":              "授权完成数据无效",
		"PENDING_AUTH_SESSION_CONSUMED":                "授权会话已使用",
		"PENDING_AUTH_SESSION_CREATE_FAILED":           "创建授权会话失败",
		"PENDING_AUTH_SESSION_EXPIRED":                 "授权会话已过期",
		"PENDING_AUTH_SESSION_NOT_FOUND":               "授权会话不存在",
		"PENDING_AUTH_SESSION_UPDATE_FAILED":           "更新授权会话失败",
		"PENDING_AUTH_TARGET_USER_MISSING":             "授权目标用户缺失",
		"PENDING_AUTH_TARGET_USER_NOT_FOUND":           "授权目标用户不存在",
		"PROXY_BACKUP_REQUIRED":                        "请配置备用代理",
		"PROXY_BACKUP_SELF":                            "备用代理不能是自身",
		"PROXY_IN_USE":                                 "代理正在使用中，不能删除",
		"PROXY_NOT_FOUND":                              "代理不存在",
		"PROXY_WARN_DAYS_INVALID":                      "代理到期提醒天数无效",
		"SUBSCRIPTION_REPOSITORY_UNAVAILABLE":          "订阅服务暂时不可用",
		"USAGE_CLEANUP_INVALID_CANCELLER":              "用量清理取消人无效",
		"USAGE_CLEANUP_INVALID_CREATOR":                "用量清理创建人无效",
		"USAGE_CLEANUP_INVALID_RANGE":                  "用量清理时间范围无效",
		"USAGE_CLEANUP_MISSING_RANGE":                  "请选择用量清理时间范围",
		"USAGE_CLEANUP_RANGE_TOO_LARGE":                "用量清理时间范围过大",
		"USAGE_LOG_NOT_FOUND":                          "用量日志不存在",
		"VERIFY_CODE_MAX_ATTEMPTS":                     "验证码尝试次数过多，请重新获取",
		"VERIFY_CODE_TOO_FREQUENT":                     "验证码发送过于频繁，请稍后再试",
		"ACCESS_TOKEN_EXPIRED":                         "访问令牌已过期，请重新授权",
		"INVITATION_CODE_INVALID":                      "邀请码无效",
		"INVITATION_CODE_REQUIRED":                     "请输入邀请码",
		"INVALID_RESET_TOKEN":                          "重置链接无效或已过期",
		"INVALID_VERIFY_CODE":                          "验证码无效",
		"MISSING_API_KEY":                              "缺少 API Key",
		"MISSING_PARAMETER":                            "缺少必要参数",
		"NO_AVAILABLE_INSTANCE":                        "当前没有可用实例",
		"NOTIFY_CODE_USER_RATE_LIMIT":                  "验证码发送过于频繁，请稍后再试",
		"PROMO_CODE_ALREADY_USED":                      "优惠码已使用",
		"PROMO_CODE_DISABLED":                          "优惠码已停用",
		"PROMO_CODE_EXPIRED":                           "优惠码已过期",
		"PROMO_CODE_INVALID":                           "优惠码无效",
		"PROMO_CODE_MAX_USED":                          "优惠码使用次数已达上限",
		"PROMO_CODE_NOT_FOUND":                         "优惠码不存在",
		"REFRESH_TOKEN_EXPIRED":                        "登录状态已过期，请重新登录",
		"REFRESH_TOKEN_INVALID":                        "登录状态无效，请重新登录",
		"REFRESH_TOKEN_REUSED":                         "登录状态异常，请重新登录",
		"REFUND_AMOUNT_EXCEEDED":                       "退款金额超出可退金额",
		"REFUND_DISABLED":                              "退款功能未启用",
		"REFUND_FAILED":                                "退款失败，请稍后重试",
		"REFUND_QUERY_UNSUPPORTED":                     "当前支付渠道不支持查询退款",
		"REGISTRATION_DISABLED":                        "注册功能暂未开放",
		"RESTORE_IN_PROGRESS":                          "恢复任务正在执行中",
		"SAME_GROUP":                                   "目标分组与当前分组相同",
		"SERVER_SHUTTING_DOWN":                         "服务正在关闭，请稍后重试",
		"SETTING_NOT_FOUND":                            "设置项不存在",
		"SETTING_SERVICE_UNAVAILABLE":                  "设置服务暂时不可用",
		"SYSTEM_OPERATION_BUSY":                        "系统操作正在执行中，请稍后再试",
		"SYSTEM_OPERATION_ID_REQUIRED":                 "缺少系统操作 ID",
		"TOKEN_EXPIRED":                                "令牌已过期",
		"TOKEN_REVOKED":                                "令牌已撤销",
		"TOKEN_TOO_LARGE":                              "令牌内容过大",
		"TOO_MANY_NOTIFY_EMAILS":                       "通知邮箱数量过多",
		"TOO_MANY_PENDING":                             "待处理请求过多，请稍后再试",
		"UNSUPPORTED_PLATFORM":                         "平台不支持",
		"WXPAY_CONFIG_INVALID_KEY":                     "微信支付密钥无效",
		"WXPAY_CONFIG_INVALID_KEY_LENGTH":              "微信支付密钥长度无效",
		"WXPAY_CONFIG_MISSING_KEY":                     "微信支付密钥未配置",
	},
	errorLocaleEnglish: {
		"AUTH_REQUIRED":                                "Please sign in before continuing.",
		"UNAUTHORIZED":                                 "Please sign in before continuing.",
		"INVALID_USER":                                 "The user does not exist or the session is invalid.",
		"BACKEND_MODE_ADMIN_ONLY":                      "Backend mode is active. Only admin login is allowed.",
		"SERVICE_UNAVAILABLE":                          "The service is temporarily unavailable. Please try again later.",
		"CONFIG_NOT_READY":                             "System configuration is not ready.",
		"VALIDATION_ERROR":                             "Request validation failed.",
		"INVALID_REQUEST":                              "Invalid request.",
		"OAUTH_DISABLED":                               "OAuth login is disabled.",
		"PENDING_AUTH_NOT_READY":                       "The authorization service is temporarily unavailable. Please try again later.",
		"PENDING_AUTH_SESSION_INVALID":                 "The authorization session is invalid or expired. Please start again.",
		"PENDING_AUTH_TARGET_USER_MISMATCH":            "The authorization session must be completed by the targeted user.",
		"USER_EMAIL_CONFLICT":                          "This email matches multiple users. Please contact an administrator.",
		"AUTH_IDENTITY_OWNERSHIP_CONFLICT":             "This third-party identity is already bound to another user.",
		"AUTH_IDENTITY_CHANNEL_OWNERSHIP_CONFLICT":     "This third-party identity channel is already bound to another user.",
		"SUBSCRIPTION_NOT_FOUND":                       "Subscription not found.",
		"SUBSCRIPTION_EXPIRED":                         "The subscription has expired.",
		"SUBSCRIPTION_SUSPENDED":                       "The subscription is suspended.",
		"SUBSCRIPTION_ALREADY_EXISTS":                  "This user already has a subscription for this plan.",
		"SUBSCRIPTION_ASSIGN_CONFLICT":                 "This user already has a subscription, and the new assignment conflicts with it.",
		"SUBSCRIPTION_DUPLICATE_CONFIRMATION_REQUIRED": "This user already has a subscription for this plan. Confirm to overwrite the existing subscription.",
		"SUBSCRIPTION_NOT_REVOKED":                     "The subscription is not revoked and cannot be restored.",
		"SUBSCRIPTION_RESTORE_CONFLICT":                "This user already has an active subscription for the same plan.",
		"GROUP_NOT_SUBSCRIPTION_TYPE":                  "The target group is not a subscription plan.",
		"DAILY_LIMIT_EXCEEDED":                         "Daily usage limit exceeded.",
		"WEEKLY_LIMIT_EXCEEDED":                        "Weekly usage limit exceeded.",
		"MONTHLY_LIMIT_EXCEEDED":                       "Monthly usage limit exceeded.",
		"TOTAL_LIMIT_EXCEEDED":                         "Total usage limit exceeded.",
		"SUBSCRIPTION_NIL_INPUT":                       "Subscription input cannot be empty.",
		"ADJUST_WOULD_EXPIRE":                          "The adjustment would make the subscription expire immediately.",
		"CANNOT_SHORTEN_EXPIRED":                       "Expired subscriptions cannot be shortened.",
		"OPS_REPO_UNAVAILABLE":                         "The operations log service is temporarily unavailable.",
		"OPS_FILTER_REQUIRED":                          "A filter is required.",
		"OPS_TIME_RANGE_REQUIRED":                      "Start time and end time are required.",
		"OPS_TIME_RANGE_INVALID":                       "Start time must not be later than end time.",
		"OPS_ERROR_NOT_FOUND":                          "Error log not found.",
		"OPS_ERROR_INVALID_ID":                         "Invalid error log ID.",
		"OPS_ERROR_LOAD_FAILED":                        "Failed to load the error log.",
		"TURNSTILE_VERIFICATION_FAILED":                "Human verification failed. Please try again.",
		"TURNSTILE_NOT_CONFIGURED":                     "Human verification is not configured.",
		"TURNSTILE_INVALID_SECRET_KEY":                 "Invalid human verification secret key.",
		"TOTP_NOT_ENABLED":                             "Two-factor authentication is not enabled.",
		"TOTP_ALREADY_ENABLED":                         "Two-factor authentication is already enabled for this account.",
		"TOTP_NOT_SETUP":                               "Two-factor authentication is not set up for this account.",
		"TOTP_INVALID_CODE":                            "Invalid two-factor authentication code.",
		"TOTP_SETUP_EXPIRED":                           "The two-factor setup session has expired.",
		"TOTP_TOO_MANY_ATTEMPTS":                       "Too many verification attempts. Please try again later.",
		"TOTP_VERIFY_ERROR":                            "Two-factor verification failed. Please try again.",
		"VERIFY_CODE_REQUIRED":                         "Email verification code is required.",
		"PASSWORD_REQUIRED":                            "Password is required.",
		"EMAIL_VERIFY_NOT_ENABLED":                     "Email verification is not enabled.",
		"REDEEM_CODE_EXPIRY_CONFLICT":                  "expires_at and expires_in_days cannot both be set.",
		"REDEEM_CODE_EXPIRES_IN_DAYS_INVALID":          "expires_in_days must be greater than zero.",
		"REDEEM_CODE_EXPIRES_AT_INVALID":               "expires_at must be in the future.",
		"REDEEM_CODE_CONFLICT":                         "Redeem code conflict or already used by another user.",
		"ACCOUNT_NIL_INPUT":                            "Account input cannot be empty.",
		"ACCOUNT_NOT_FOUND":                            "Account not found.",
		"ACCOUNT_NOT_IN_FALLBACK":                      "The account is not in fallback state.",
		"API_KEY_EXISTS":                               "API Key already exists.",
		"API_KEY_EXPIRED":                              "API Key has expired.",
		"API_KEY_INACTIVE":                             "API Key is inactive.",
		"API_KEY_INVALID_CHARS":                        "API Key contains invalid characters.",
		"API_KEY_NOT_FOUND":                            "API Key not found.",
		"API_KEY_QUOTA_EXHAUSTED":                      "API Key quota has been exhausted.",
		"API_KEY_RATE_1D_EXCEEDED":                     "API Key daily usage limit exceeded.",
		"API_KEY_RATE_5H_EXCEEDED":                     "API Key 5-hour usage limit exceeded.",
		"API_KEY_RATE_7D_EXCEEDED":                     "API Key 7-day usage limit exceeded.",
		"API_KEY_RATE_LIMITED":                         "API Key requests are too frequent. Please try again later.",
		"API_KEY_TOO_SHORT":                            "API Key is too short.",
		"BALANCE_NOT_ENOUGH":                           "Insufficient balance.",
		"INSUFFICIENT_BALANCE":                         "Insufficient balance.",
		"BALANCE_PAYMENT_DISABLED":                     "Balance payment is disabled.",
		"BILLING_SERVICE_ERROR":                        "Billing service is temporarily unavailable.",
		"CANCEL_RATE_LIMITED":                          "Cancel requests are too frequent. Please try again later.",
		"CHANNEL_EXISTS":                               "Channel already exists.",
		"CHANNEL_NOT_FOUND":                            "Channel not found.",
		"EMAIL_EXISTS":                                 "Email is already in use.",
		"EMAIL_NOT_CONFIGURED":                         "Email service is not configured.",
		"EMAIL_NOT_FOUND":                              "Email not found.",
		"EMAIL_RESERVED":                               "This email cannot be used.",
		"EMAIL_SUFFIX_NOT_ALLOWED":                     "This email domain is not allowed.",
		"EMAIL_VERIFY_REQUIRED":                        "Email verification is required.",
		"FORBIDDEN":                                    "You do not have permission to perform this action.",
		"GROUP_EXISTS":                                 "Group already exists.",
		"GROUP_IS_SUBSCRIPTION":                        "This group is a subscription plan group.",
		"GROUP_NOT_ACTIVE":                             "Group is not active.",
		"GROUP_NOT_ALLOWED":                            "This user is not allowed to use the group.",
		"GROUP_NOT_EXCLUSIVE":                          "This group is not exclusive.",
		"GROUP_NOT_FOUND":                              "Group not found.",
		"GROUP_RPM_EXCEEDED":                           "Group request rate limit exceeded.",
		"GROUP_TYPE_MISMATCH":                          "Group type mismatch.",
		"INSUFFICIENT_PERMISSIONS":                     "Insufficient permissions.",
		"INVALID_AMOUNT":                               "Invalid amount.",
		"INVALID_CHANNEL_ID":                           "Invalid channel ID.",
		"INVALID_CREDENTIALS":                          "Invalid email or password.",
		"INVALID_EMAIL":                                "Invalid email format.",
		"INVALID_GROUP_ID":                             "Invalid group ID.",
		"INVALID_GROUP_FILTER":                         "Invalid group filter.",
		"INVALID_INPUT":                                "Invalid input.",
		"INVALID_MODE":                                 "Invalid mode.",
		"INVALID_MODERATION_TEST_IMAGE":                "Invalid moderation test image.",
		"INVALID_OUT_TRADE_NO":                         "Invalid merchant order number.",
		"INVALID_PLATFORM":                             "Invalid platform.",
		"INVALID_STATUS":                               "Invalid status.",
		"NOT_FOUND":                                    "Record not found.",
		"ORDER_EXPIRED":                                "Order has expired.",
		"ORDER_NOT_FOUND":                              "Order not found.",
		"PAYMENT_DISABLED":                             "Payment is disabled.",
		"PAYMENT_GATEWAY_ERROR":                        "Payment gateway error. Please try again later.",
		"PLAN_GROUP_REQUIRED":                          "Plan group is required.",
		"PLAN_NAME_REQUIRED":                           "Plan name is required.",
		"PLAN_NOT_FOUND":                               "Plan not found.",
		"PLAN_NOT_AVAILABLE":                           "Plan is not available.",
		"PLAN_ORIGINAL_PRICE_INVALID":                  "Invalid original plan price.",
		"PLAN_PRICE_INVALID":                           "Invalid plan price.",
		"PLAN_VALIDITY_REQUIRED":                       "Plan validity is required.",
		"PLAN_VALIDITY_UNIT_REQUIRED":                  "Plan validity unit is required.",
		"PENDING_ORDERS":                               "There are pending orders. This action cannot be performed now.",
		"PAYMENT_PROVIDER_MISCONFIGURED":               "Payment provider is not configured correctly. Please contact an administrator.",
		"REDEEM_CODE_BATCH_UPDATE_EMPTY":               "There are no redeem codes to update.",
		"REDEEM_CODE_BATCH_UPDATE_IDS_REQUIRED":        "Select redeem codes to update.",
		"REDEEM_CODE_BATCH_UPDATE_INVALID":             "Invalid redeem code batch update request.",
		"REDEEM_CODE_BATCH_UPDATE_INVALID_ID":          "Invalid redeem code ID.",
		"REDEEM_CODE_CORE_FIELDS_IMMUTABLE":            "Used redeem codes cannot have core fields changed.",
		"REDEEM_CODE_DELETE_USED":                      "Used redeem codes cannot be deleted.",
		"REDEEM_CODE_EXPIRED":                          "Redeem code has expired.",
		"REDEEM_CODE_GROUP_ID_INVALID":                 "Invalid redeem code group.",
		"REDEEM_CODE_INVALID":                          "Invalid redeem code.",
		"REDEEM_CODE_LOCKED":                           "Redeem code is being processed. Please try again later.",
		"REDEEM_CODE_NOT_FOUND":                        "Redeem code not found.",
		"REDEEM_CODE_STATUS_INVALID":                   "Invalid redeem code status.",
		"REDEEM_CODE_UNSUPPORTED_TYPE":                 "Redeem code type is not supported.",
		"REDEEM_CODE_USED":                             "Redeem code has already been used.",
		"REDEEM_RATE_LIMITED":                          "Redeem requests are too frequent. Please try again later.",
		"SUBSCRIPTION_INVALID":                         "Subscription is invalid or expired.",
		"SUBSCRIPTION_REQUIRED":                        "A valid subscription is required for this group.",
		"USER_NOT_FOUND":                               "User not found.",
		"USER_DISABLED":                                "User is disabled.",
		"USER_INACTIVE":                                "User is inactive.",
		"USER_NOT_ACTIVE":                              "User is not active.",
		"USER_PLATFORM_DAILY_QUOTA_EXHAUSTED":          "Daily quota for this platform has been exhausted.",
		"USER_PLATFORM_WEEKLY_QUOTA_EXHAUSTED":         "Weekly quota for this platform has been exhausted.",
		"USER_PLATFORM_MONTHLY_QUOTA_EXHAUSTED":        "Monthly quota for this platform has been exhausted.",
		"USER_REFUND_DISABLED":                         "Refunds are disabled for this user.",
		"USER_RPM_EXCEEDED":                            "User request rate limit exceeded.",
		"AVATAR_INVALID":                               "Invalid avatar.",
		"AVATAR_NOT_IMAGE":                             "Avatar file is not an image.",
		"AVATAR_TOO_LARGE":                             "Avatar file is too large.",
		"AFFILIATE_ALREADY_BOUND":                      "This user already has an affiliate binding.",
		"AFFILIATE_CODE_INVALID":                       "Invalid affiliate code.",
		"AFFILIATE_CODE_TAKEN":                         "Affiliate code is already in use.",
		"AFFILIATE_PROFILE_NOT_FOUND":                  "Affiliate profile not found.",
		"AFFILIATE_QUOTA_EMPTY":                        "Affiliate quota cannot be empty.",
		"ANNOUNCEMENT_INPUT_REQUIRED":                  "Announcement input is required.",
		"ANNOUNCEMENT_INVALID_TARGET":                  "Invalid announcement targeting rules.",
		"ANNOUNCEMENT_NOT_FOUND":                       "Announcement not found.",
		"ANNOUNCEMENT_STATUS_INVALID":                  "Invalid announcement status.",
		"ANNOUNCEMENT_TITLE_INVALID":                   "Invalid announcement title.",
		"ATTRIBUTE_DEFINITION_NOT_FOUND":               "Attribute definition not found.",
		"ATTRIBUTE_KEY_EXISTS":                         "Attribute key already exists.",
		"ATTRIBUTE_VALIDATION_FAILED":                  "Attribute validation failed.",
		"AUTH_IDENTITY_BIND_FAILED":                    "Failed to bind the third-party identity.",
		"AUTH_IDENTITY_CHANNEL_LOOKUP_FAILED":          "Failed to inspect the third-party identity channel.",
		"AUTH_IDENTITY_EMAIL_MISMATCH":                 "The third-party identity email does not match the current email.",
		"AUTH_IDENTITY_LOOKUP_FAILED":                  "Failed to inspect the third-party identity.",
		"AUTH_IDENTITY_USER_LOOKUP_FAILED":             "Failed to load the third-party identity user.",
		"BACKUP_IN_PROGRESS":                           "Backup is already in progress.",
		"BACKUP_NOT_COMPLETED":                         "Backup is not completed yet.",
		"BACKUP_NOT_FOUND":                             "Backup not found.",
		"BACKUP_RECORDS_CORRUPT":                       "Backup records are corrupted.",
		"BACKUP_S3_CONFIG_CORRUPT":                     "S3 backup configuration is corrupted.",
		"BACKUP_S3_NOT_CONFIGURED":                     "S3 backup is not configured.",
		"CONTENT_MODERATION_HASH_CACHE_UNAVAILABLE":    "Content moderation hash cache is temporarily unavailable.",
		"IDENTITY_PROVIDER_INVALID":                    "Invalid identity provider.",
		"IDENTITY_REDIRECT_INVALID":                    "Invalid identity redirect URL.",
		"OAUTH_BROWSER_SESSION_GEN_FAILED":             "Failed to generate the OAuth browser session.",
		"OAUTH_BUILD_URL_FAILED":                       "Failed to build the OAuth authorization URL.",
		"OAUTH_CONFIG_INVALID":                         "OAuth configuration is invalid.",
		"OAUTH_EMAIL_NOT_VERIFIED":                     "The OAuth account email is not verified.",
		"OAUTH_INVITATION_REQUIRED":                    "An invitation code is required to register with this OAuth account.",
		"OAUTH_NONCE_GEN_FAILED":                       "Failed to generate the OAuth nonce.",
		"OAUTH_PKCE_GEN_FAILED":                        "Failed to generate the OAuth PKCE verifier.",
		"OAUTH_PROVIDER_INVALID":                       "Invalid OAuth provider.",
		"OAUTH_PROVIDER_NOT_FOUND":                     "OAuth provider not found.",
		"OAUTH_STATE_GEN_FAILED":                       "Failed to generate the OAuth state.",
		"OAUTH_SUBJECT_MISSING":                        "The OAuth account is missing a subject identifier.",
		"OPS_ALERT_EVENT_NOT_FOUND":                    "Alert event not found.",
		"OPS_ALERT_RULE_NOT_FOUND":                     "Alert rule not found.",
		"OPS_DISABLED":                                 "Operations monitoring is disabled.",
		"OPS_GROUP_ID_INVALID":                         "Invalid operations group ID.",
		"OPS_PAGE_INVALID":                             "Invalid page number.",
		"OPS_PAGE_SIZE_INVALID":                        "Invalid page size.",
		"OPS_PAGINATION_CONFLICT":                      "Pagination parameters conflict.",
		"OPS_PREAGG_NOT_READY":                         "Pre-aggregated operations data is not ready.",
		"OPS_SYSTEM_LOG_CLEANUP_FAILED":                "Failed to clean up system logs.",
		"OPS_SYSTEM_LOG_CLEANUP_FILTER_REQUIRED":       "System log cleanup requires filters.",
		"OPS_SYSTEM_LOG_CLEANUP_INVALID_OPERATOR":      "Invalid system log cleanup operator.",
		"OPS_SYSTEM_LOG_CLEANUP_INVALID_RANGE":         "Invalid system log cleanup time range.",
		"OPS_SYSTEM_LOG_LIST_FAILED":                   "Failed to list system logs.",
		"OPS_TIME_RANGE_TOO_LARGE":                     "The query time range is too large.",
		"OPS_TOPN_INVALID":                             "Invalid TopN parameter.",
		"PASSWORD_INCORRECT":                           "Incorrect password.",
		"PASSWORD_RESET_DISABLED":                      "Password reset is disabled.",
		"PASSWORD_TOO_SHORT":                           "Password is too short.",
		"PENDING_AUTH_ADOPTION_APPLY_FAILED":           "Failed to apply the pending OAuth profile.",
		"PENDING_AUTH_ADOPTION_LOAD_FAILED":            "Failed to load the pending OAuth profile.",
		"PENDING_AUTH_ADOPTION_SAVE_FAILED":            "Failed to save the pending OAuth profile.",
		"PENDING_AUTH_BIND_APPLY_FAILED":               "Failed to bind the pending OAuth identity.",
		"PENDING_AUTH_BROWSER_MISMATCH":                "The authorization browser session does not match.",
		"PENDING_AUTH_CODE_CONSUMED":                   "The authorization code has already been used.",
		"PENDING_AUTH_CODE_EXPIRED":                    "The authorization code has expired.",
		"PENDING_AUTH_CODE_INVALID":                    "Invalid authorization code.",
		"PENDING_AUTH_COMPLETION_INVALID":              "Invalid authorization completion payload.",
		"PENDING_AUTH_SESSION_CONSUMED":                "The authorization session has already been used.",
		"PENDING_AUTH_SESSION_CREATE_FAILED":           "Failed to create the authorization session.",
		"PENDING_AUTH_SESSION_EXPIRED":                 "The authorization session has expired.",
		"PENDING_AUTH_SESSION_NOT_FOUND":               "Authorization session not found.",
		"PENDING_AUTH_SESSION_UPDATE_FAILED":           "Failed to update the authorization session.",
		"PENDING_AUTH_TARGET_USER_MISSING":             "The authorization target user is missing.",
		"PENDING_AUTH_TARGET_USER_NOT_FOUND":           "The authorization target user was not found.",
		"PROXY_BACKUP_REQUIRED":                        "Backup proxy is required.",
		"PROXY_BACKUP_SELF":                            "Backup proxy cannot be itself.",
		"PROXY_IN_USE":                                 "Proxy is in use and cannot be deleted.",
		"PROXY_NOT_FOUND":                              "Proxy not found.",
		"PROXY_WARN_DAYS_INVALID":                      "Invalid proxy expiry warning days.",
		"SUBSCRIPTION_REPOSITORY_UNAVAILABLE":          "Subscription service is temporarily unavailable.",
		"USAGE_CLEANUP_INVALID_CANCELLER":              "Invalid usage cleanup canceller.",
		"USAGE_CLEANUP_INVALID_CREATOR":                "Invalid usage cleanup creator.",
		"USAGE_CLEANUP_INVALID_RANGE":                  "Invalid usage cleanup time range.",
		"USAGE_CLEANUP_MISSING_RANGE":                  "Usage cleanup time range is required.",
		"USAGE_CLEANUP_RANGE_TOO_LARGE":                "Usage cleanup time range is too large.",
		"USAGE_LOG_NOT_FOUND":                          "Usage log not found.",
		"VERIFY_CODE_MAX_ATTEMPTS":                     "Too many verification attempts. Please request a new code.",
		"VERIFY_CODE_TOO_FREQUENT":                     "Verification code requests are too frequent. Please try again later.",
		"ACCESS_TOKEN_EXPIRED":                         "Access token has expired. Please authorize again.",
		"INVITATION_CODE_INVALID":                      "Invalid invitation code.",
		"INVITATION_CODE_REQUIRED":                     "Invitation code is required.",
		"INVALID_RESET_TOKEN":                          "The reset link is invalid or expired.",
		"INVALID_VERIFY_CODE":                          "Invalid verification code.",
		"MISSING_API_KEY":                              "API Key is required.",
		"MISSING_PARAMETER":                            "A required parameter is missing.",
		"NO_AVAILABLE_INSTANCE":                        "No available instance.",
		"NOTIFY_CODE_USER_RATE_LIMIT":                  "Verification code requests are too frequent. Please try again later.",
		"PROMO_CODE_ALREADY_USED":                      "Promo code has already been used.",
		"PROMO_CODE_DISABLED":                          "Promo code is disabled.",
		"PROMO_CODE_EXPIRED":                           "Promo code has expired.",
		"PROMO_CODE_INVALID":                           "Invalid promo code.",
		"PROMO_CODE_MAX_USED":                          "Promo code usage limit has been reached.",
		"PROMO_CODE_NOT_FOUND":                         "Promo code not found.",
		"REFRESH_TOKEN_EXPIRED":                        "Session has expired. Please sign in again.",
		"REFRESH_TOKEN_INVALID":                        "Session is invalid. Please sign in again.",
		"REFRESH_TOKEN_REUSED":                         "Session is abnormal. Please sign in again.",
		"REFUND_AMOUNT_EXCEEDED":                       "Refund amount exceeds the refundable amount.",
		"REFUND_DISABLED":                              "Refunds are disabled.",
		"REFUND_FAILED":                                "Refund failed. Please try again later.",
		"REFUND_QUERY_UNSUPPORTED":                     "This payment provider does not support refund queries.",
		"REGISTRATION_DISABLED":                        "Registration is currently disabled.",
		"RESTORE_IN_PROGRESS":                          "Restore is already in progress.",
		"SAME_GROUP":                                   "The target group is the same as the current group.",
		"SERVER_SHUTTING_DOWN":                         "Server is shutting down. Please try again later.",
		"SETTING_NOT_FOUND":                            "Setting not found.",
		"SETTING_SERVICE_UNAVAILABLE":                  "Setting service is temporarily unavailable.",
		"SYSTEM_OPERATION_BUSY":                        "Another system operation is in progress. Please try again later.",
		"SYSTEM_OPERATION_ID_REQUIRED":                 "System operation ID is required.",
		"TOKEN_EXPIRED":                                "Token has expired.",
		"TOKEN_REVOKED":                                "Token has been revoked.",
		"TOKEN_TOO_LARGE":                              "Token payload is too large.",
		"TOO_MANY_NOTIFY_EMAILS":                       "Too many notification emails.",
		"TOO_MANY_PENDING":                             "Too many pending requests. Please try again later.",
		"UNSUPPORTED_PLATFORM":                         "Unsupported platform.",
		"WXPAY_CONFIG_INVALID_KEY":                     "Invalid WeChat Pay key.",
		"WXPAY_CONFIG_INVALID_KEY_LENGTH":              "Invalid WeChat Pay key length.",
		"WXPAY_CONFIG_MISSING_KEY":                     "WeChat Pay key is not configured.",
	},
}

var localizedDirectErrorMessages = map[string]map[string]string{
	errorLocaleChinese: {
		"API key not found":                                                  "API Key 不存在",
		"API key service is not configured":                                  "API Key 服务未配置",
		"API key service not available":                                      "API Key 服务暂时不可用",
		"Auth service not configured":                                        "认证服务未配置",
		"Error requests view is disabled":                                    "错误请求查看功能未启用",
		"Failed to get API key usage stats":                                  "获取 API Key 用量统计失败",
		"Failed to get API key usage trend":                                  "获取 API Key 用量趋势失败",
		"Failed to get advanced settings":                                    "获取高级设置失败",
		"Failed to get alert runtime settings":                               "获取告警运行设置失败",
		"Failed to get dashboard statistics":                                 "获取仪表盘统计失败",
		"Failed to get email notification config":                            "获取邮件通知配置失败",
		"Failed to get group capacity summary":                               "获取分组容量汇总失败",
		"Failed to get group statistics":                                     "获取分组统计失败",
		"Failed to get group usage summary":                                  "获取分组用量汇总失败",
		"Failed to get metric thresholds":                                    "获取指标阈值失败",
		"Failed to get model statistics":                                     "获取模型统计失败",
		"Failed to get runtime log config":                                   "获取运行日志配置失败",
		"Failed to get usage trend":                                          "获取用量趋势失败",
		"Failed to get user breakdown stats":                                 "获取用户拆分统计失败",
		"Failed to get user spending ranking":                                "获取用户消费排行失败",
		"Failed to get user usage stats":                                     "获取用户用量统计失败",
		"Failed to get user usage trend":                                     "获取用户用量趋势失败",
		"Failed to generate menu item ID":                                    "生成菜单项 ID 失败",
		"Failed to list request details":                                     "获取请求详情列表失败",
		"Failed to parse request body":                                       "请求体解析失败",
		"Failed to read request body":                                        "读取请求体失败",
		"Failed to sync upstream models from upstream":                       "从上游同步模型失败",
		"Invalid API key ID":                                                 "API Key ID 无效",
		"Invalid account ID":                                                 "账号 ID 无效",
		"Invalid announcement ID":                                            "公告 ID 无效",
		"Invalid api_key_id":                                                 "API Key ID 无效",
		"Invalid billing_mode":                                               "计费模式无效",
		"Invalid billing_type":                                               "计费类型无效",
		"Invalid end_date format, use YYYY-MM-DD":                            "结束日期格式无效，请使用 YYYY-MM-DD",
		"Invalid group ID":                                                   "分组 ID 无效",
		"Invalid group_id":                                                   "分组 ID 无效",
		"Invalid hostname format":                                            "主机名格式无效",
		"Invalid id":                                                         "ID 无效",
		"Invalid key ID":                                                     "API Key ID 无效",
		"Invalid model_source, user usage only supports requested":           "模型来源无效，用户用量只支持 requested",
		"Invalid request":                                                    "请求参数无效",
		"Invalid start_date format, use YYYY-MM-DD":                          "开始日期格式无效，请使用 YYYY-MM-DD",
		"Invalid status_code":                                                "状态码无效",
		"Invalid stream value, use true or false":                            "stream 参数无效，请使用 true 或 false",
		"Invalid subscription ID":                                            "订阅 ID 无效",
		"Invalid usage ID":                                                   "用量记录 ID 无效",
		"Invalid user ID":                                                    "用户 ID 无效",
		"Invalid user_id":                                                    "用户 ID 无效",
		"Invalid port number":                                                "端口号无效",
		"Invalid username format":                                            "用户名格式无效",
		"Invalid database name format":                                       "数据库名称格式无效",
		"Invalid SSL mode":                                                   "SSL 模式无效",
		"Invalid Redis database number (0-15)":                               "Redis 数据库编号无效，请使用 0-15",
		"Invalid database hostname":                                          "数据库主机名无效",
		"Invalid database port":                                              "数据库端口无效",
		"Invalid database username":                                          "数据库用户名无效",
		"Invalid database name":                                              "数据库名称无效",
		"Invalid Redis hostname":                                             "Redis 主机名无效",
		"Invalid Redis port":                                                 "Redis 端口无效",
		"Invalid Redis database number":                                      "Redis 数据库编号无效",
		"Invalid admin email format":                                         "管理员邮箱格式无效",
		"Invalid server port":                                                "服务端口无效",
		"Invalid server mode (must be 'release' or 'debug')":                 "服务模式无效，必须是 release 或 debug",
		"Image generation is not enabled for this group":                     "当前分组未启用图片生成",
		"Not authorized to access this API key's usage":                      "无权访问该 API Key 的用量",
		"Not authorized to access this API key's usage records":              "无权访问该 API Key 的用量记录",
		"Not authorized to access this record":                               "无权访问该记录",
		"Ops service not available":                                          "运维服务暂时不可用",
		"Pending oauth session provider mismatch":                            "待处理授权会话的提供方不匹配",
		"Rate limit service unavailable":                                     "限流服务暂时不可用",
		"Request body is empty":                                              "请求体不能为空",
		"Setup is not allowed: system is already installed":                  "系统已安装，不能再次执行初始化",
		"Subscription not found":                                             "订阅不存在",
		"Too many API key IDs (maximum 100 allowed)":                         "API Key ID 数量过多，最多允许 100 个",
		"Usage cleanup service unavailable":                                  "用量清理服务暂时不可用",
		"User not authenticated":                                             "请先登录",
		"User not found in context":                                          "请先登录",
		"Unauthorized":                                                       "请先登录",
		"account_ids is required":                                            "请选择账号",
		"account_ids or filters is required":                                 "请选择账号或筛选条件",
		"backup ID is required":                                              "备份 ID 不能为空",
		"failed to parse request body":                                       "请求体解析失败",
		"image file is required":                                             "必须上传图片文件",
		"images endpoint requires an image model":                            "图片接口需要使用图片模型",
		"images[].file_id is not supported (use images[].image_url instead)": "images[].file_id 不支持，请改用 images[].image_url",
		"images[].image_url is required":                                     "images[].image_url 不能为空",
		"incorrect admin password":                                           "管理员密码不正确",
		"invalid images field type":                                          "images 字段类型无效",
		"invalid n field type":                                               "n 字段类型无效",
		"invalid output_compression field type":                              "output_compression 字段类型无效",
		"invalid output_compression field value":                             "output_compression 字段值无效",
		"invalid partial_images field type":                                  "partial_images 字段类型无效",
		"invalid partial_images field value":                                 "partial_images 字段值无效",
		"invalid stream field type":                                          "stream 字段类型无效",
		"invalid stream field value":                                         "stream 字段值无效",
		"mask.file_id is not supported (use mask.image_url instead)":         "mask.file_id 不支持，请改用 mask.image_url",
		"n must be a positive integer":                                       "n 必须是正整数",
		"n must be greater than 0":                                           "n 必须大于 0",
		"notification email service is not configured":                       "通知邮件服务未配置",
		"password is required for restore operation":                         "恢复操作需要输入密码",
		"platform quota service not available":                               "平台额度服务暂时不可用",
		"refresh_token is required":                                          "refresh_token 不能为空",
		"request body is empty":                                              "请求体不能为空",
		"token is required":                                                  "token 不能为空",
		"unauthorized":                                                       "请先登录",
	},
}

func localizeErrorMessage(c *gin.Context, reason string, fallback string) string {
	reason = strings.TrimSpace(reason)
	locale := requestErrorLocale(c)
	if locale == "" {
		return fallback
	}
	if reason != "" {
		if byReason, ok := localizedErrorMessages[locale]; ok {
			if message, ok := byReason[reason]; ok && strings.TrimSpace(message) != "" {
				return message
			}
		}
	}
	return localizeDirectErrorMessage(locale, fallback)
}

func localizeDirectErrorMessage(locale string, fallback string) string {
	fallback = strings.TrimSpace(fallback)
	if fallback == "" {
		return fallback
	}
	if byMessage, ok := localizedDirectErrorMessages[locale]; ok {
		if message, ok := byMessage[fallback]; ok && strings.TrimSpace(message) != "" {
			return message
		}
	}
	if locale != errorLocaleChinese {
		return fallback
	}

	if strings.HasPrefix(fallback, "Invalid request: ") {
		return "请求参数无效：" + strings.TrimPrefix(fallback, "Invalid request: ")
	}
	if strings.HasPrefix(fallback, "images endpoint requires an image model, got ") {
		return "图片接口需要使用图片模型，当前模型为 " + strings.TrimPrefix(fallback, "images endpoint requires an image model, got ")
	}
	if strings.HasPrefix(fallback, "Invalid ") && strings.HasSuffix(fallback, " ID") {
		field := strings.TrimSuffix(strings.TrimPrefix(fallback, "Invalid "), " ID")
		if label := localizedIDFieldName(field); label != "" {
			return label + " ID 无效"
		}
		return field + " ID 无效"
	}
	if strings.HasPrefix(fallback, "Invalid ") && strings.Contains(fallback, " value, use true or false") {
		field := strings.TrimSuffix(strings.TrimPrefix(fallback, "Invalid "), " value, use true or false")
		return field + " 参数无效，请使用 true 或 false"
	}
	if strings.HasPrefix(fallback, "Failed to ") {
		return "操作失败：" + strings.TrimPrefix(fallback, "Failed to ")
	}
	if strings.HasSuffix(strings.ToLower(fallback), " not found") {
		subject := strings.TrimSpace(fallback[:len(fallback)-len(" not found")])
		if label := localizedIDFieldName(subject); label != "" {
			return label + "不存在"
		}
	}
	return fallback
}

func localizedIDFieldName(field string) string {
	switch strings.ToLower(strings.TrimSpace(field)) {
	case "account":
		return "账号"
	case "api key", "key":
		return "API Key"
	case "announcement":
		return "公告"
	case "backup":
		return "备份"
	case "channel":
		return "渠道"
	case "error log":
		return "错误日志"
	case "group":
		return "分组"
	case "profile":
		return "配置"
	case "promo code":
		return "优惠码"
	case "rule":
		return "规则"
	case "subscription":
		return "订阅"
	case "usage":
		return "用量记录"
	case "user":
		return "用户"
	}
	return ""
}

func requestErrorLocale(c *gin.Context) string {
	if c == nil || c.Request == nil {
		return ""
	}
	raw := strings.ToLower(strings.TrimSpace(c.GetHeader("Accept-Language")))
	for _, part := range strings.Split(raw, ",") {
		tag := strings.TrimSpace(part)
		if semi := strings.IndexByte(tag, ';'); semi >= 0 {
			tag = strings.TrimSpace(tag[:semi])
		}
		switch {
		case tag == "zh" || strings.HasPrefix(tag, "zh-") || strings.HasPrefix(tag, "zh_"):
			return errorLocaleChinese
		case tag == "en" || strings.HasPrefix(tag, "en-") || strings.HasPrefix(tag, "en_"):
			return errorLocaleEnglish
		}
	}
	return ""
}
